language: node_js
node_js:
  - "8"
  - "9"
  - "10"
before_install:
  - export TZ=America/Los_Angeles
install:
  # Qt
  - npm install
  - export PATH=$PWD/node_modules/.bin:$PATH
  - export NODE_OPTIONS="--max-old-space-size=3072"
script:
  - npm run clean test
branches:
  only:
    - master
dist: trusty
